const ACTION_TYPES = {
    REQUEST_USERS_PENDING:'REQUEST_USERS_PENDING',
    REQUEST_USERS_SUCCESS:'REQUEST_USERS_SUCCESS',
    REQUEST_USERS_FAILED:'REQUEST_USERS_FAILED',
    DELETE_USER:"DELETE_USER",
    SAVE_USER:"SAVE_USER",
};


export default ACTION_TYPES;